using Microsoft.AspNetCore.Authentication.JwtBearer;
using Microsoft.EntityFrameworkCore;
using Microsoft.IdentityModel.Tokens;
using SriKaaliYouth.Api.Data;
using System.Text;
using Microsoft.OpenApi.Models;

var builder = WebApplication.CreateBuilder(args);

builder.Services.AddControllers();

builder.Services.AddEndpointsApiExplorer();
builder.Services.AddSwaggerGen(options =>
{
    options.AddSecurityDefinition("Bearer", new OpenApiSecurityScheme
    {
        Name = "Authorization",
        Type = SecuritySchemeType.Http,
        Scheme = "bearer",
        BearerFormat = "JWT",
        In = ParameterLocation.Header,
        Description = "Enter your JWT token"
    });

    options.AddSecurityRequirement(new OpenApiSecurityRequirement
    {
        {
            new OpenApiSecurityScheme
            {
                Reference = new OpenApiReference
                {
                    Type = ReferenceType.SecurityScheme,
                    Id = "Bearer"
                }
            },
            Array.Empty<string>()
        }
    });
});

// PostgreSQL
builder.Services.AddDbContext<AppDbContext>(options =>
    options.UseNpgsql(
        builder.Configuration.GetConnectionString("DefaultConnection")
    )
);

// JWT
var jwtKey = builder.Configuration["Jwt:Key"];

if (string.IsNullOrWhiteSpace(jwtKey))
{
    throw new InvalidOperationException(
        "JWT Key is not configured."
    );
}

builder.Services
    .AddAuthentication(JwtBearerDefaults.AuthenticationScheme)
    .AddJwtBearer(options =>
    {
        options.TokenValidationParameters =
            new TokenValidationParameters
            {
                ValidateIssuer = true,
                ValidateAudience = true,
                ValidateLifetime = true,
                ValidateIssuerSigningKey = true,

                ValidIssuer =
                    builder.Configuration["Jwt:Issuer"],

                ValidAudience =
                    builder.Configuration["Jwt:Audience"],

                IssuerSigningKey =
                    new SymmetricSecurityKey(
                        Encoding.UTF8.GetBytes(jwtKey)
                    ),

                RoleClaimType = System.Security.Claims.ClaimTypes.Role,
                ClockSkew = TimeSpan.Zero
            };
    });

builder.Services.AddCors(options =>
{
    options.AddPolicy("FrontendPolicy", policy =>
    {
        policy
            .WithOrigins(
                "http://localhost:5173",
                "https://sri-kaali-youth-frontend.onrender.com"
            )
            .AllowAnyHeader()
            .AllowAnyMethod();
    });
});

var app = builder.Build();

// Auto Database Schema Migration Helper for status column and member_login_requests table
using (var scope = app.Services.CreateScope())
{
    try
    {
        var context = scope.ServiceProvider.GetRequiredService<AppDbContext>();
        context.Database.ExecuteSqlRaw(@"
            ALTER TABLE users ADD COLUMN IF NOT EXISTS status text DEFAULT 'Approved';
            UPDATE users SET status = 'Approved' WHERE status IS NULL OR status = '';

            CREATE TABLE IF NOT EXISTS member_login_requests (
                id integer GENERATED BY DEFAULT AS IDENTITY,
                user_id integer NOT NULL,
                request_token text NOT NULL,
                requested_at timestamp with time zone NOT NULL,
                status text NOT NULL DEFAULT 'Pending',
                approved_by_user_id integer NULL,
                approved_at timestamp with time zone NULL,
                rejected_at timestamp with time zone NULL,
                expires_at timestamp with time zone NOT NULL,
                consumed_at timestamp with time zone NULL,
                CONSTRAINT ""PK_member_login_requests"" PRIMARY KEY (id),
                CONSTRAINT ""FK_member_login_requests_users_user_id"" FOREIGN KEY (user_id) REFERENCES users (user_id) ON DELETE CASCADE,
                CONSTRAINT ""FK_member_login_requests_users_approved_by_user_id"" FOREIGN KEY (approved_by_user_id) REFERENCES users (user_id)
            );

            CREATE INDEX IF NOT EXISTS ""IX_member_login_requests_approved_by_user_id"" ON member_login_requests (approved_by_user_id);
            CREATE INDEX IF NOT EXISTS ""IX_member_login_requests_user_id"" ON member_login_requests (user_id);

            CREATE TABLE IF NOT EXISTS ""__EFMigrationsHistory"" (
                ""MigrationId"" character varying(150) NOT NULL,
                ""ProductVersion"" character varying(32) NOT NULL,
                CONSTRAINT ""PK___EFMigrationsHistory"" PRIMARY KEY (""MigrationId"")
            );

            INSERT INTO ""__EFMigrationsHistory"" (""MigrationId"", ""ProductVersion"")
            VALUES ('20260821034856_AddMemberLoginApprovalAndRoles', '8.0.0')
            ON CONFLICT DO NOTHING;

            INSERT INTO ""__EFMigrationsHistory"" (""MigrationId"", ""ProductVersion"")
            VALUES ('20260821041142_AddUserAccountStatus', '8.0.0')
            ON CONFLICT DO NOTHING;
        ");
    }
    catch (Exception ex)
    {
        Console.WriteLine($"DB Schema Init: {ex.Message}");
    }
}


    app.UseSwagger();
    app.UseSwaggerUI();


app.UseHttpsRedirection();

app.UseCors("FrontendPolicy");

app.UseAuthentication();

app.UseAuthorization();

app.MapControllers();

app.Run();