// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SriKaaliYouth.Api.Data;

#nullable disable

namespace SriKaaliYouth.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260821041142_AddUserAccountStatus")]
    partial class AddUserAccountStatus
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SriKaaliYouth.Api.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("category_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("category_name");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Icon")
                        .HasColumnType("text")
                        .HasColumnName("icon");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.HasKey("CategoryId");

                    b.ToTable("categories");
                });

            modelBuilder.Entity("SriKaaliYouth.Api.Models.Donation", b =>
                {
                    b.Property<int>("DonationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("donation_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("DonationId"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric")
                        .HasColumnName("amount");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("integer")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("DonationDate")
                        .HasColumnType("date")
                        .HasColumnName("donation_date");

                    b.Property<string>("DonorName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("donor_name");

                    b.Property<int>("FestivalId")
                        .HasColumnType("integer")
                        .HasColumnName("festival_id");

                    b.Property<string>("PaymentMode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("payment_mode");

                    b.Property<string>("ReceiverName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("receiver_name");

                    b.Property<string>("VillageArea")
                        .HasColumnType("text")
                        .HasColumnName("village_area");

                    b.HasKey("DonationId");

                    b.ToTable("donations");
                });

            modelBuilder.Entity("SriKaaliYouth.Api.Models.Expense", b =>
                {
                    b.Property<int>("ExpenseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("expense_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ExpenseId"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric")
                        .HasColumnName("amount");

                    b.Property<int?>("CategoryId")
                        .HasColumnType("integer")
                        .HasColumnName("category_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("integer")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("ExpenseDate")
                        .HasColumnType("date")
                        .HasColumnName("expense_date");

                    b.Property<string>("ExpenseType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("expense_type");

                    b.Property<int?>("FestivalDay")
                        .HasColumnType("integer")
                        .HasColumnName("festival_day");

                    b.Property<int>("FestivalId")
                        .HasColumnType("integer")
                        .HasColumnName("festival_id");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("item_name");

                    b.Property<string>("PaymentMode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("payment_mode");

                    b.HasKey("ExpenseId");

                    b.ToTable("expenses");
                });

            modelBuilder.Entity("SriKaaliYouth.Api.Models.FestivalEvent", b =>
                {
                    b.Property<int>("FestivalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("festival_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("FestivalId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("end_date");

                    b.Property<string>("FestivalName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("festival_name");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.Property<int>("Year")
                        .HasColumnType("integer")
                        .HasColumnName("year");

                    b.HasKey("FestivalId");

                    b.ToTable("festival_events");
                });

            modelBuilder.Entity("SriKaaliYouth.Api.Models.LuckyDrawEntry", b =>
                {
                    b.Property<int>("LuckyDrawId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("lucky_draw_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("LuckyDrawId"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric")
                        .HasColumnName("amount");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("integer")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("EntryDate")
                        .HasColumnType("date")
                        .HasColumnName("entry_date");

                    b.Property<int>("FestivalId")
                        .HasColumnType("integer")
                        .HasColumnName("festival_id");

                    b.Property<string>("MobileNumber")
                        .HasColumnType("text")
                        .HasColumnName("mobile_number");

                    b.Property<string>("PaymentMode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("payment_mode");

                    b.Property<string>("PersonName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("person_name");

                    b.Property<string>("ReceiverName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("receiver_name");

                    b.Property<string>("TicketNumber")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ticket_number");

                    b.HasKey("LuckyDrawId");

                    b.ToTable("lucky_draw_entries");
                });

            modelBuilder.Entity("SriKaaliYouth.Api.Models.MemberLoginRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("approved_at");

                    b.Property<int?>("ApprovedByUserId")
                        .HasColumnType("integer")
                        .HasColumnName("approved_by_user_id");

                    b.Property<DateTime?>("ConsumedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("consumed_at");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<DateTime?>("RejectedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("rejected_at");

                    b.Property<string>("RequestToken")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("request_token");

                    b.Property<DateTime>("RequestedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("requested_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("ApprovedByUserId");

                    b.HasIndex("UserId");

                    b.ToTable("member_login_requests");
                });

            modelBuilder.Entity("SriKaaliYouth.Api.Models.Sponsor", b =>
                {
                    b.Property<int>("SponsorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("sponsor_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SponsorId"));

                    b.Property<string>("Contribution")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("contribution");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("integer")
                        .HasColumnName("created_by");

                    b.Property<int>("FestivalId")
                        .HasColumnType("integer")
                        .HasColumnName("festival_id");

                    b.Property<string>("SponsorName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("sponsor_name");

                    b.Property<string>("VillageArea")
                        .HasColumnType("text")
                        .HasColumnName("village_area");

                    b.HasKey("SponsorId");

                    b.ToTable("sponsors");
                });

            modelBuilder.Entity("SriKaaliYouth.Api.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UserId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("MobileNumber")
                        .HasColumnType("text")
                        .HasColumnName("mobile_number");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("role");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("username");

                    b.HasKey("UserId");

                    b.ToTable("users");
                });

            modelBuilder.Entity("SriKaaliYouth.Api.Models.VelampataEntry", b =>
                {
                    b.Property<int>("VelampataId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("velampata_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("VelampataId"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric")
                        .HasColumnName("amount");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("integer")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("EntryDate")
                        .HasColumnType("date")
                        .HasColumnName("entry_date");

                    b.Property<int>("FestivalId")
                        .HasColumnType("integer")
                        .HasColumnName("festival_id");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("item_name");

                    b.Property<string>("PaymentMode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("payment_mode");

                    b.Property<string>("PersonName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("person_name");

                    b.Property<string>("ReceiverName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("receiver_name");

                    b.HasKey("VelampataId");

                    b.ToTable("velampata_entries");
                });

            modelBuilder.Entity("SriKaaliYouth.Api.Models.MemberLoginRequest", b =>
                {
                    b.HasOne("SriKaaliYouth.Api.Models.User", "ApprovedByUser")
                        .WithMany()
                        .HasForeignKey("ApprovedByUserId");

                    b.HasOne("SriKaaliYouth.Api.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApprovedByUser");

                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
